# -*- coding: utf-8 -*-
"""Retail_BI_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16K74VvrBeKjyy-jDo3juOgzye4KZYFGl
"""

import pandas as pd
import numpy as np

df = pd.read_csv('train.csv.zip')
df.head()

df.info()

df.describe()

df.isnull().sum()

df = df.dropna()
df.isnull().sum()

df = df.dropna()

df.isnull().sum()

df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d/%m/%Y')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%d/%m/%Y')

df.info()

df['Year'] = df['Order Date'].dt.year
df['Month'] = df['Order Date'].dt.month
df['Month_Name'] = df['Order Date'].dt.month_name()
df['Day'] = df['Order Date'].dt.day

df.head()

df['Sales'].sum()

df.groupby('Region')['Sales'].sum().sort_values(ascending=False)

df.groupby('Category')['Sales'].sum().sort_values(ascending=False)

df.groupby('Customer Name')['Sales'].sum().sort_values(ascending=False).head(10)

df.groupby(['Year','Month'])['Sales'].sum()

dim_customer = df[['Customer ID','Customer Name','Segment']].drop_duplicates()

dim_product = df[['Product ID','Product Name','Category','Sub-Category']].drop_duplicates()

dim_region = df[['Region','State','City']].drop_duplicates()

dim_date = df[['Order Date','Year','Month','Month_Name','Day']].drop_duplicates()

fact_sales = df[['Order ID','Customer ID','Product ID','Region',
                 'Order Date','Sales']]

dim_customer.to_csv('dim_customer.csv', index=False)
dim_product.to_csv('dim_product.csv', index=False)
dim_region.to_csv('dim_region.csv', index=False)
dim_date.to_csv('dim_date.csv', index=False)
fact_sales.to_csv('fact_sales.csv', index=False)

import os
os.listdir()

from google.colab import files

files.download('dim_customer.csv')
files.download('dim_product.csv')
files.download('dim_region.csv')
files.download('dim_date.csv')
files.download('fact_sales.csv')